Repository mt-mods/mail, pull requests merged in 2023-06, with the labels that each got.

#98 partial fox for #97
  storage.lua
Labels: bug

#100 Add trash
  init.lua
  locale/mail.de.tr
  locale/mail.es.tr
  locale/mail.fr.tr
  locale/mail.hu.tr
  locale/mail.pt_BR.tr
  locale/mail.zh_CN.tr
  locale/mail.zh_TW.tr
  locale/template.txt
  storage.lua
  ui/drafts.lua
  ui/events.lua
  ui/inbox.lua
  ui/mail.lua
  ui/outbox.lua
  ui/settings.lua
  ui/trash.lua
Labels: enhancement

#104 cache storage entries and batch them for write-back
  storage.lua
Labels: enhancement

#105 update german translation (+templates)
  locale/mail.de.tr
  locale/mail.es.tr
  locale/mail.fr.tr
  locale/mail.hu.tr
  locale/mail.pt_BR.tr
  locale/mail.zh_CN.tr
  locale/mail.zh_TW.tr
  locale/template.txt
  mail.hu.tr
  ui/about.lua
Labels: documentation, enhancement
