Repository mt-mods/mail, pull requests merged in 2023-04, with the labels that each got.

#44 german translation
  locale/mail.de.tr
Labels: documentation, enhancement

#46 Fix message notifications
  api.lua
  hud.lua
  onjoin.lua
Labels: bug

#47 Fix read messages becoming unread while migrating
  migrate.lua
Labels: bug

#48 zh_TW translation
  locale/mail.zh_TW.tr
Labels: documentation, enhancement

#49 Fix maillists issues
  storage.lua
  ui/edit_maillists.lua
  ui/maillists.lua
Labels: bug

#32 add screenshot / update readme / prepare for cdb release
  README.md
  pics/ingame.png
  screenshot_1.png
  screenshot_2.png
Labels: documentation, enhancement

#53 Fix permanent HUD
  ui/message.lua
Labels: bug

#54 Fix blank messages
  ui/compose.lua
Labels: bug

#56 Message filters/sorters
  chatcommands.lua
  locale/mail.de.tr
  locale/mail.fr.tr
  locale/mail.zh_TW.tr
  locale/template.txt
  storage.lua
  ui/events.lua
  ui/inbox.lua
  ui/mail.lua
  ui/outbox.lua
Labels: enhancement

#58 Simplify sorting and make it more readable
  chatcommands.lua
  init.lua
  storage.lua
  ui/events.lua
  ui/inbox.lua
  ui/outbox.lua
Labels: bug

#60 Add multiple selection
  init.lua
  locale/mail.de.tr
  locale/mail.fr.tr
  locale/mail.zh_TW.tr
  locale/template.txt
  ui/drafts.lua
  ui/events.lua
  ui/inbox.lua
  ui/message.lua
  ui/outbox.lua
Labels: enhancement

#62 Update about for 1.1.0
  ui/about.lua
Labels: documentation

#65 Fix close button which makes the formspec blinking
  ui/events.lua
Labels: bug

#66 Fix header click + use them as sorting
  ui/events.lua
Labels: bug, enhancement

#67 Fix oversized selected number
  ui/events.lua
Labels: bug

#68 1.1.x
  ui/about.lua
  ui/events.lua
Labels: release

#69 Fix lag with multiple selection action
  storage.lua
  ui/events.lua
Labels: bug

#73 update testing harness / move contact-list function to util
  .github/workflows/test.yml
  docker-compose.yml
  gui.lua
  init.lua
  test/Dockerfile
  util/contact.lua
Labels: enhancement

#75 Fix message infos
  ui/message.lua
  ui/outbox.lua
Labels: bug

#78 Message reply fixes
  ui/events.lua
  ui/mail.lua
Labels: bug

#82 crash fixes
  ui/events.lua
Labels: bug
