Repository mt-mods/mail, pull requests merged in 2024-08, with the labels that each got.

#148 Update api.md docs
  api.md
Labels: Documentation

#149 Update files to 1.4
  README.md
  screenshot_1.4.0_1.png
  screenshot_1.4.0_2.png
  ui/about.lua
Labels: Release

#151 Optimize performance of the inbox
  ui/inbox.lua
Labels: Performance

#153 Add support for a get_keys() equivalent for lower than 5.7 Minetest versions
  migrate.lua
Labels: Bug, Release blocker, Cleanup
