Repository mt-mods/mail, pull requests merged in 2024-03, with the labels that each got.

#140 Cleanly handle player mailling lists
  api.lua
  api.spec.lua
  storage.lua
Labels: bug

#142 Implement grouping by contribution type
  ui/about.lua
Labels: enhancement

#141 Adjusted options UI
  ui/about.lua
  ui/settings.lua
Labels: documentation, enhancement
